### ISSUE TITLE
Dropdown menu 

### ISSUE THREAD

**Issue by bugrakilic** [ebru/oysayim#2]
Merhaba, güzel düşünülmüş bir çözüm öncelikle elinize sağlık. Okul ve sandık için oluşturulmuş text box'lar belki dropdown menüye çevrilebilir. Böylece belki İl ve İlçe de aynı mantıkla eklenebilir. Data Oy ve Ötesi'nden çekilebilir eğer buna müsaitse.

**Comment by ebru** [comment]
Merhaba tesekkurler, bu daha kapsamli bir oy sayim sisteminde gerekli olacaktir fakat su an icin kapsam buna dahil degil.
