### ISSUE TITLE
Sayım sonucunun kaydedilmesi 

### ISSUE THREAD

**Issue by bugrakilic** [ebru/oysayim#3]
Sandık oy sayım işlemi kesin olarak tamamlanınca Kaydet gibi bir butonla son durum DB'ye veya basit bir csv file'a yazılabilir. Tabi bu kayıt da yine resmi belge olmayacaktır, kolayca manipüle edilebilir. Yine de oyların akıbeti hakkında yüzeysel bir fikir sağlayabilir.

**Comment by ebru** [comment]
Merhaba tesekkurler, gecerli bir authentication sistemi gerekecektir bunun icin fakat bu su anki kapsami asan bir durum maalesef.
