### ISSUE TITLE
Tasarım önerileri ve örnekleri

### ISSUE THREAD

**Issue by volkantash** [ebru/oysayim#9]
Telefondan kullanılacağı için küçük bir örnek yaptım. 

Oy ekleme ve oy çıkarma yerine +1 -1 yazdım. Bunları uç yerlere koyup yanlışlıkla basılmasının önüne geçmek istedim.

![resim](https://github.com/ebru/oysayim/assets/25375593/6a8b6860-4cbf-43fa-87a8-d1fd8c56a5a1)

**Comment by ebru** [comment]
Tesekkurler, oy pusulasindaki siranin algida daha kolay olacagi geri donusleri nedeniyle, var olan yerlesimde devam etmeye karar verdik su an icin.
